# analysis_options.yaml docs: https://www.dartlang.org/guides/language/analysis-options
analyzer:
  # Strong mode is required. Applies to the current project.
  strong-mode:
    # When compiling to JS, both implicit options apply to the current
    # project and all dependencies. They are useful to find possible
    # Type fixes or areas for explicit typing.
    implicit-casts: true
    implicit-dynamic: true

# ALL lint rules are included. Unused lints should be commented
# out with a reason. An up to date list of all options is here
# http://dart-lang.github.io/linter/lints/options/options.html
# Descriptions of each rule is here http://dart-lang.github.io/linter/lints/
#
# To ignore a lint rule on a case by case basic in code just add a comment
# above it or at the end of the line like: // ignore: <linter rule>
# example: // ignore: invalid_assignment, const_initialized_with_non_constant_value
#
# More info about configuring analysis_options.yaml files
# https://www.dartlang.org/guides/language/analysis-options#excluding-lines-within-a-file
linter:
  rules:
    # Prefer single quotes where they won't require escape sequences.
    # http://dart-lang.github.io/linter/lints/prefer_single_quotes.html
    # recommendation: recommended
    # 0 issues
    - prefer_single_quotes
