name: github
version: 7.0.3
description: A high-level GitHub API Client Library that uses Github's v3 API
homepage: https://github.com/SpinlockLabs/github.dart

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'

dependencies:
  http: '^0.12.0'
  http_parser: ^3.1.1
  json_annotation: '>=2.0.0 <4.0.0'
  meta: ^1.1.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  json_serializable: ^3.2.2
  mockito: ^3.0.0
  pedantic: ^1.0.0
  test: ^1.3.0
  yaml: ^2.2.0

dependency_overrides:
  http: ^0.13.0-nullsafety.0
  http_parser: ^4.0.0-nullsafety
  json_annotation: ^4.0.0-nullsafety.0 
  json_serializable: ^4.0.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6
  mockito: ^5.0.0-nullsafety.5
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.17
  yaml: ^3.0.0-nullsafety.0