name: Require semver:* and unreleased Label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 1
          labels: "semver:patch, semver:minor, semver:major"
          token: ${{secrets.MACHINE_GITHUB_API_TOKEN}}
          add_comment: |
            Add a semantic version label
            semver:patch - non-breaking bug fixes or internal changes
            semver:minor - non-breaking changes (additions, deprecations)
            semver:major - contains changes that may break consumers 
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 1
          labels: "unreleased"
          token: ${{secrets.MACHINE_GITHUB_API_TOKEN}}
          add_comment: The unrelease label is required to track which PRs have yet to be released.